apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: vannggoc/auth
          env:
            - name: MONGO_URI
              value: 'mongodb+srv://soleil:01636878201@cluster0.4x48u.mongodb.net/auth?retryWrites=true&w=majority&appName=Cluster0'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: AUTH_MAIL
              valueFrom:
                secretKeyRef:
                  name: auth-mail
                  key: AUTH_MAIL
            - name: AUTH_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-pass
                  key: AUTH_PASS
            - name: AUTH_REDIS_HOST
              value: auth-redis-srv
            - name: OTP_TIME
              valueFrom:
                secretKeyRef:
                  name: otp-time
                  key: OTP_TIME
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: kimbeautyspa
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
