apiVersion: apps/v1
kind: Deployment
metadata:
  name: branchs-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: branchs
  template:
    metadata:
      labels:
        app: branchs
    spec:
      containers:
        - name: branchs
          image: vannggoc/branchs
          env:
            - name: MONGO_URI
              value: 'mongodb+srv://soleil:01636878201@cluster0.4x48u.mongodb.net/branchs?retryWrites=true&w=majority&appName=Cluster0'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: kimbeautyspa
            - name: PER_PAGE
              valueFrom:
                secretKeyRef:
                  name: per-page
                  key: PER_PAGE
---
apiVersion: v1
kind: Service
metadata:
  name: branchs-srv
spec:
  selector:
    app: branchs
  ports:
    - name: branchs
      protocol: TCP
      port: 3000
      targetPort: 3000
