apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: kimbeautyspa.com
      http:
        paths:
          - path: /users/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /rules/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: rules-srv
                port:
                  number: 3000
          - path: /accounts/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: accounts-srv
                port:
                  number: 3000
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
