apiVersion: apps/v1
kind: Deployment
metadata:
  name: shifts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shifts
  template:
    metadata:
      labels:
        app: shifts
    spec:
      containers:
        - name: shifts
          image: vannggoc/shifts
          env:
            - name: MONGO_URI
              value: 'mongodb+srv://soleil:01636878201@cluster0.4x48u.mongodb.net/shifts?retryWrites=true&w=majority&appName=Cluster0'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: kimbeautyspa
            - name: PER_PAGE
              valueFrom:
                secretKeyRef:
                  name: per-page
                  key: PER_PAGE
---
apiVersion: v1
kind: Service
metadata:
  name: shifts-srv
spec:
  selector:
    app: shifts
  ports:
    - name: shifts
      protocol: TCP
      port: 3000
      targetPort: 3000
