name: deploy-services

on:
  push:
    branches:
      - main
    paths:
      - 'services/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd services && docker build -t vannggoc/services .
      - run: docker push vannggoc/services
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save 105ee2a1-7bee-45e0-95d8-f53484f69c72
      - run: kubectl rollout restart deployment services-depl
