name: deploy-products

on:
  push:
    branches:
      - main
    paths:
      - 'products/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd products && docker build -t vannggoc/products .
      - run: docker push vannggoc/products
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save d1ebc16f-2588-4daf-8776-cb8df6e65963
      - run: kubectl rollout restart deployment products-depl
