name: deploy-branchs

on:
  push:
    branches:
      - main
    paths:
      - 'branchs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd branchs && docker build -t vannggoc/branchs .
      - run: docker push vannggoc/branchs
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save 4e16a30e-5889-46c1-8bf1-c04c6b477bb5
      - run: kubectl rollout restart deployment branchs-depl
