name: deploy-appointments

on:
  push:
    branches:
      - main
    paths:
      - 'appointments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd appointments && docker build -t vannggoc/appointments .
      - run: docker push vannggoc/appointments
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save f2ad5602-3065-47d5-8c0b-3c4911982b12
      - run: kubectl rollout restart deployment appointments-depl
