name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save 1031dd6a-06e7-4dbb-abf7-8ce5c2cfe8d9
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
